import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Navigate,Link,NavLink,useNavigate,useLocation} from 'react-router-dom';
import {QRCodeSVG} from 'qrcode.react';
import './style.css';

type Scenario={id:string;title:string;moment:string;situation:string;question:string;options:string[];correctIndex:number;explanation:string;reminder:string};
type Progress={completedScenarioIds:string[];quizBestScore:number;quizAttempts:number;confidenceBefore?:number;confidenceAfter?:number;lastQuizWrongIds?:string[]};
type Profile={fullName:string;userId:string;address:string;birthdate:string;phoneNumber:string;email:string;photoData:string;mfaEnabled:boolean;role:string};

const PASSWORD_MESSAGE='Password requirements at least 12 characters (UPPERCASE, lowercase, a number, special characters eg ?=.*[@$!%*?&]).';
const passwordStrong=(p:string)=>p.length>=12&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/[0-9]/.test(p)&&/[@$!%*?&]/.test(p);

async function rawReq<T>(url:string,options:RequestInit={}):Promise<T>{
 const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
 if(!r.ok){let msg=`Request failed (${r.status})`;try{const j=await r.json();msg=j.message||msg}catch{};throw new Error(msg)}
 return r.status===204?undefined as T:await r.json();
}
let refreshing:Promise<boolean>|null=null;
async function refreshToken(){
 if(!refreshing) refreshing=rawReq('/api/auth/refresh',{method:'POST'}).then(()=>true).catch(()=>false).finally(()=>{refreshing=null});
 return refreshing;
}
async function req<T>(url:string,options:RequestInit={},retry=true):Promise<T>{
 try{return await rawReq<T>(url,options)}catch(e){
  if(retry && e instanceof Error && e.message.startsWith('Request failed (401)') && !url.includes('/api/auth/refresh')){
   if(await refreshToken()) return req<T>(url,options,false);
  }
  throw e;
 }
}
const api={
 register:(email:string,password:string)=>rawReq<any>('/api/auth/register',{method:'POST',body:JSON.stringify({email,password})}),
 login:(email:string,password:string)=>rawReq<any>('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})}),
 verify:(code:string)=>rawReq<any>('/api/auth/mfa/verify',{method:'POST',body:JSON.stringify({code})}),
 verifyRegistrationMfa:(code:string)=>rawReq<any>('/api/auth/register/mfa/verify',{method:'POST',body:JSON.stringify({code})}),
 forgotPassword:(email:string)=>rawReq<any>('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email})}),
 resetPassword:(token:string,newPassword:string)=>rawReq<any>('/api/auth/reset-password',{method:'POST',body:JSON.stringify({token,newPassword})}),
 me:()=>req<any>('/api/auth/me'),
 logout:()=>req<void>('/api/auth/logout',{method:'POST'},false),
 revokeAll:()=>req<any>('/api/auth/revoke-all',{method:'POST'}),
 profile:()=>req<Profile>('/api/profile'),
 saveProfile:(p:Partial<Profile>)=>req<Profile>('/api/profile',{method:'PUT',body:JSON.stringify(p)}),
 changeEmail:(currentPassword:string,newEmail:string)=>req<Profile>('/api/profile/email',{method:'POST',body:JSON.stringify({currentPassword,newEmail})}),
 changePassword:(currentPassword:string,newPassword:string)=>req<any>('/api/profile/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})}),
 enableMfa:(password:string)=>req<any>('/api/profile/mfa/enable',{method:'POST',body:JSON.stringify({password})}),
 verifyEnableMfa:(code:string)=>req<any>('/api/profile/mfa/enable/verify',{method:'POST',body:JSON.stringify({code})}),
 disableMfa:(password:string)=>req<any>('/api/profile/mfa/disable',{method:'POST',body:JSON.stringify({password})}),
 resetMfa:(password:string)=>req<any>('/api/profile/mfa/reset',{method:'POST',body:JSON.stringify({password})}),
 deleteAccount:(password:string)=>req<any>('/api/profile',{method:'DELETE',body:JSON.stringify({password})}),
 scenarios:()=>req<Scenario[]>('/api/scenarios'),
 progress:()=>req<Progress>('/api/progress'),
 saveProgress:(p:Progress)=>req<void>('/api/progress',{method:'PUT',body:JSON.stringify(p)})
};
const emptyProgress=():Progress=>({completedScenarioIds:[],quizBestScore:0,quizAttempts:0,lastQuizWrongIds:[]});

function PasswordRequirements({password,show}:{password:string;show:boolean}){
 if(!show)return null;
 return <div className={passwordStrong(password)?'password-help valid':'password-help'}>{PASSWORD_MESSAGE}</div>;
}
function Header({profile}:{profile:Profile}){const n=useNavigate();const initials=(profile.fullName||profile.email||'S').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return <header className="topbar"><div className="brand-wrap"><Link to="/" className="brand"><span className="brand-mark">S</span><span>SECURE OSHC LEARNING</span></Link></div><nav className="main-menu"><NavLink to="/">Home</NavLink><NavLink to="/profile">Student Profile</NavLink><NavLink to="/settings">Settings</NavLink><NavLink to="/payment">Payment Method</NavLink><NavLink to="/scenarios">Scenarios</NavLink><NavLink to="/quiz">Quiz</NavLink><NavLink to="/progress">Progress</NavLink></nav><button className="profile-chip" title="Open Student Profile" onClick={()=>n('/profile')}>{profile.photoData?<img src={profile.photoData} alt="Student profile"/>:<span>{initials}</span>}</button></header>}
function Shell({children}:{children:React.ReactNode}){const[p,setP]=React.useState<Profile|null>(null);const[loading,setLoading]=React.useState(true);const n=useNavigate();React.useEffect(()=>{api.profile().then(setP).catch(()=>n('/login')).finally(()=>setLoading(false))},[n]);if(loading)return <div className="loading">Loading secure OSHC learning...</div>;if(!p)return null;return <><Header profile={p}/><main>{children}</main></>}
function Private({children}:{children:React.ReactNode}){const[a,setA]=React.useState<boolean|null>(null);React.useEffect(()=>{api.me().then(x=>setA(!!x.authenticated)).catch(()=>setA(false))},[]);if(a===null)return <div className="loading">Checking secure identity...</div>;return a?<Shell>{children}</Shell>:<Navigate to="/login" replace/>}

function Login(){const[email,setEmail]=React.useState('');const[p,setP]=React.useState('');const[code,setCode]=React.useState('');const[setupUri,setSetupUri]=React.useState('');const[mfa,setMfa]=React.useState(false);const[registrationMfa,setRegistrationMfa]=React.useState(false);const[e,setE]=React.useState('');const n=useNavigate();return <div className="auth-page"><div className="auth card"><div className="brand-large"><span className="brand-mark">S</span><b>SECURE OSHC LEARNING</b></div><h1>{registrationMfa?'Complete MFA registration':mfa?'Verify your identity':'Student sign in'}</h1><p>{registrationMfa?'Scan the QR code with your authenticator app, then enter the six-digit code. MFA is required to finish creating your account.':mfa?'Enter the six-digit code from your TOTP authenticator.':'Secure access to scenarios, quiz, progress and student settings.'}</p>{registrationMfa?<><div className="qr-panel"><QRCodeSVG value={setupUri} size={180} includeMargin/><div><p><b>Step 1:</b> Scan this QR code with Google Authenticator, Microsoft Authenticator or another compatible TOTP app.</p><p><b>Step 2:</b> Enter the six-digit code generated by the app.</p><label>Authenticator code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={x=>setCode(x.target.value.replace(/\D/g,''))} placeholder="123456"/></label><button disabled={code.length!==6} onClick={async()=>{setE('');try{await api.verifyRegistrationMfa(code);n('/')}catch(x){setE(x instanceof Error?x.message:'Invalid authenticator code')}}}>Verify MFA & create account</button><button className="secondary" onClick={()=>{setRegistrationMfa(false);setSetupUri('');setCode('')}}>Back</button></div></div></>:!mfa?<><label>Email<input type="email" autoComplete="username" value={email} onChange={x=>setEmail(x.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={p} onChange={x=>setP(x.target.value)}/></label><button onClick={async()=>{setE('');try{const r=await api.login(email,p);if(r.registrationMfaRequired){setSetupUri(r.otpauthUri);setRegistrationMfa(true)}else if(r.mfaRequired)setMfa(true);else n('/')}catch(x){setE(x instanceof Error?x.message:'Login failed')}}}>Continue</button><p className="auth-link"><Link to="/forgot-password">I forgot the password</Link></p><p className="auth-link">New student? <Link to="/register">Create an account</Link></p></>:<><label>Authenticator code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={x=>setCode(x.target.value.replace(/\D/g,''))} placeholder="123456"/></label><button disabled={code.length!==6} onClick={async()=>{setE('');try{await api.verify(code);n('/')}catch(x){setE(x instanceof Error?x.message:'Invalid authenticator code')}}}>Verify and enter</button><button className="secondary" onClick={()=>{setMfa(false);setCode('')}}>Back</button></>}{e&&<div className="error">{e}</div>}</div></div>}

function Register(){const[email,setEmail]=React.useState('');const[p,setP]=React.useState('');const[c,setC]=React.useState('');const[e,setE]=React.useState('');const n=useNavigate();const[setupUri,setSetupUri]=React.useState('');const[code,setCode]=React.useState('');const[mfaStep,setMfaStep]=React.useState(false);return <div className="auth-page"><div className="auth card"><div className="brand-large"><span className="brand-mark">S</span><b>SECURE OSHC LEARNING</b></div><h1>{mfaStep?'Set up MFA to finish registration':'Create student account'}</h1>{!mfaStep?<><p>Your account must be protected with MFA during registration. Your password must meet every security requirement below.</p><label>Email<input type="email" autoComplete="email" value={email} onChange={x=>setEmail(x.target.value)} placeholder="student@example.com"/></label><label>Password<input type="password" autoComplete="new-password" value={p} onChange={x=>setP(x.target.value)}/><PasswordRequirements password={p} show={p.length>0}/></label><label>Confirm password<input type="password" autoComplete="new-password" value={c} onChange={x=>setC(x.target.value)}/>{c&&p!==c&&<div className="error">Passwords do not match.</div>}</label><button disabled={!passwordStrong(p)||p!==c} onClick={async()=>{setE('');try{const r=await api.register(email,p);if(r.registrationMfaRequired){setSetupUri(r.otpauthUri);setMfaStep(true)}}catch(x){setE(x instanceof Error?x.message:'Registration failed')}}}>Create account & continue to MFA</button>{e&&<div className="error">{e}</div>}<p className="auth-link"><Link to="/login">Back to sign in</Link></p></>:<><p><b>Step 1:</b> Scan the QR code below using your authenticator app.</p><div className="qr-panel"><QRCodeSVG value={setupUri} size={200} includeMargin/><div><p><b>Step 2:</b> Enter the six-digit code generated by the authenticator.</p><label>Authenticator code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={x=>setCode(x.target.value.replace(/\D/g,''))} placeholder="123456"/></label><button disabled={code.length!==6} onClick={async()=>{setE('');try{await api.verifyRegistrationMfa(code);n('/')}catch(x){setE(x instanceof Error?x.message:'MFA verification failed')}}}>Verify MFA & finish registration</button><button className="secondary" onClick={()=>n('/login')}>Continue later from sign in</button></div></div>{e&&<div className="error">{e}</div>}</>}</div></div>}
function ForgotPassword(){
 const[email,setEmail]=React.useState('');
 const[msg,setMsg]=React.useState('');
 const[e,setE]=React.useState('');
 const[busy,setBusy]=React.useState(false);
 return <div className="auth-page"><div className="auth card">
  <div className="brand-large"><span className="brand-mark">S</span><b>SECURE OSHC LEARNING</b></div>
  <h1>Reset your password</h1>
  <p>Enter your account email. If the account exists, password-reset instructions will be provided by the configured backend.</p>
  <label>Email<input type="email" autoComplete="email" value={email} onChange={x=>setEmail(x.target.value)} placeholder="student@example.com"/></label>
  <button disabled={!email.trim()||busy} onClick={async()=>{setE('');setMsg('');setBusy(true);try{const r=await api.forgotPassword(email.trim());setMsg(r?.message||'If the account exists, reset instructions have been issued.')}catch(x){setE(x instanceof Error?x.message:'Unable to process the request')}finally{setBusy(false)}}}>{busy?'Sending...':'Send reset instructions'}</button>
  {msg&&<div className="success">{msg}</div>}{e&&<div className="error">{e}</div>}
  <p className="auth-link"><Link to="/login">Back to sign in</Link></p>
 </div></div>
}

function ResetPassword(){
 const params=new URLSearchParams(useLocation().search);
 const[token,setToken]=React.useState(params.get('token')||'');
 const[p,setP]=React.useState('');
 const[c,setC]=React.useState('');
 const[e,setE]=React.useState('');
 const[msg,setMsg]=React.useState('');
 const n=useNavigate();
 return <div className="auth-page"><div className="auth card">
  <div className="brand-large"><span className="brand-mark">S</span><b>SECURE OSHC LEARNING</b></div>
  <h1>Choose a new password</h1>
  <p>Your new password must meet every security requirement.</p>
  <label>Reset token<input value={token} onChange={x=>setToken(x.target.value)} placeholder="Paste your reset token"/></label>
  <label>New password<input type="password" autoComplete="new-password" value={p} onChange={x=>setP(x.target.value)}/><PasswordRequirements password={p} show={p.length>0}/></label>
  <label>Confirm password<input type="password" autoComplete="new-password" value={c} onChange={x=>setC(x.target.value)}/>{c&&p!==c&&<div className="error">Passwords do not match.</div>}</label>
  <button disabled={!token||!passwordStrong(p)||p!==c} onClick={async()=>{setE('');setMsg('');try{const r=await api.resetPassword(token,p);setMsg(r?.message||'Password changed successfully. Redirecting to sign in...');setTimeout(()=>n('/login'),1000)}catch(x){setE(x instanceof Error?x.message:'Password reset failed')}}}>Change password</button>
  {msg&&<div className="success">{msg}</div>}{e&&<div className="error">{e}</div>}
  <p className="auth-link"><Link to="/login">Back to sign in</Link></p>
 </div></div>
}

function Home(){const[p,setP]=React.useState<Progress>(emptyProgress());const[profile,setProfile]=React.useState<Profile|null>(null);React.useEffect(()=>{api.progress().then(setP).catch(()=>{});api.profile().then(setProfile).catch(()=>{})},[]);const completed=p.completedScenarioIds.length;return <><section className="hero"><div className="eyebrow">OSHC HEALTHCARE MOMENTS</div><h1>Understand what to do when healthcare becomes real.</h1><p>Scenario-driven learning for international students navigating Australian healthcare, claims, bills, pharmacies, hospitals and urgent situations.</p><div className="hero-actions"><Link className="cta" to="/scenarios">Start a Healthcare Moment</Link><Link className="secondary-link" to="/progress">View progress →</Link></div></section><div className="dashboard-grid"><Link className="dashboard-card" to="/profile"><span className="icon">👤</span><div><h2>Student Profile</h2><p>{profile?.fullName||'Complete your profile'} · {profile?.userId||'Secure account'}</p></div></Link><Link className="dashboard-card" to="/settings"><span className="icon">🔐</span><div><h2>Security & Privacy</h2><p>Passwords, MFA, email, sessions and passkey readiness.</p></div></Link><Link className="dashboard-card" to="/payment"><span className="icon">💳</span><div><h2>Payment Method</h2><p>External payment navigation only; no card data stored.</p></div></Link><Link className="dashboard-card" to="/quiz"><span className="icon">🧠</span><div><h2>Knowledge Quiz</h2><p>{p.quizAttempts} attempts · best {p.quizBestScore}%</p></div></Link><Link className="dashboard-card" to="/scenarios"><span className="icon">🏥</span><div><h2>Healthcare Moments</h2><p>{completed}/8 learning scenarios completed.</p></div></Link><Link className="dashboard-card" to="/progress"><span className="icon">📈</span><div><h2>Learning Progress</h2><p>Review completion and areas requiring improvement.</p></div></Link></div><div className="security-strip"><div><b>Zero Trust</b><span>Verify before protected access.</span><b>Tokenised identity</b><span>Passwords are hashed; auth uses HttpOnly tokens.</span><b>RBAC</b><span>Student role enforced server-side.</span></div><Link to="/settings" className="cta">Security settings</Link></div></>}

function Profile(){const[p,setP]=React.useState<Profile|null>(null);const[e,setE]=React.useState('');const[msg,setMsg]=React.useState('');const n=useNavigate();React.useEffect(()=>{api.profile().then(setP).catch(()=>n('/login'))},[n]);if(!p)return <div className="loading">Loading profile...</div>;const upload=(file:File)=>{if(file.size>2_000_000){setE('Photo is too large. Please use an image under about 2 MB.');return}const r=new FileReader();r.onload=()=>setP({...p,photoData:String(r.result)});r.readAsDataURL(file)};return <><div className="page-title"><div><div className="eyebrow">STUDENT PROFILE</div><h1>Your profile</h1><p>Manage the non-clinical account information used by SmartGuide.</p></div></div><div className="profile-layout"><section className="card photo-card"><div className="photo-frame">{p.photoData?<img src={p.photoData} alt="Student profile"/>:<div className="photo-placeholder">PHOTO</div>}</div><label className="upload-btn">Upload / change photo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label><small>Prototype limit: about 2 MB.</small></section><section className="card"><div className="form-grid"><label>Full name<input value={p.fullName} onChange={e=>setP({...p,fullName:e.target.value})}/></label><label>User ID<input value={p.userId} disabled/></label><label>Address<input value={p.address} onChange={e=>setP({...p,address:e.target.value})}/></label><label>Date of birth<input type="date" value={p.birthdate} onChange={e=>setP({...p,birthdate:e.target.value})}/></label><label>Phone<input value={p.phoneNumber} onChange={e=>setP({...p,phoneNumber:e.target.value})}/></label><label>Email<input value={p.email} disabled/></label></div><div className="actions"><button onClick={async()=>{setE('');setMsg('');try{const r=await api.saveProfile(p);setP(r);setMsg('Profile saved successfully.')}catch(x){setE(x instanceof Error?x.message:'Could not save profile')}}}>Save profile</button></div>{msg&&<div className="success">{msg}</div>}{e&&<div className="error">{e}</div>}<hr/><button className="danger" onClick={async()=>{await api.logout().catch(()=>{});n('/login')}}>Sign out</button></section></div></>}

function Settings(){const[p,setP]=React.useState<Profile|null>(null);const[oldPass,setOld]=React.useState('');const[newPass,setNew]=React.useState('');const[mfaPass,setMfaPass]=React.useState('');const[emailPass,setEmailPass]=React.useState('');const[newEmail,setNewEmail]=React.useState('');const[setupUri,setSetupUri]=React.useState('');const[enableCode,setEnableCode]=React.useState('');const[message,setMessage]=React.useState('');const[error,setError]=React.useState('');const[passkey,setPasskey]=React.useState<boolean|null>(null);const n=useNavigate();React.useEffect(()=>{api.profile().then(x=>{setP(x);setNewEmail(x.email)}).catch(()=>n('/login'));setPasskey(typeof window!=='undefined'&&!!window.PublicKeyCredential)},[n]);if(!p)return <div className="loading">Loading security settings...</div>;const action=async(fn:()=>Promise<any>)=>{setMessage('');setError('');try{const r=await fn();if(r?.message)setMessage(r.message);return r}catch(x){setError(x instanceof Error?x.message:'Request failed');return null}};return <><div className="page-title"><div><div className="eyebrow">SETTINGS</div><h1>Security & Privacy</h1><p>Identity, password, MFA, email and session controls.</p></div></div><section className="security-grid"><div className="card security-card"><div className="status-row"><div><h2>Multi-factor authentication</h2><p>TOTP authenticator with QR-code setup.</p></div><span className={p.mfaEnabled?'badge good-badge':'badge'}>{p.mfaEnabled?'Enabled':'Disabled'}</span></div><label>Current password<input type="password" value={mfaPass} onChange={e=>setMfaPass(e.target.value)}/></label><div className="mini-actions"><button onClick={async()=>{const r=await action(()=>api.enableMfa(mfaPass));if(r?.otpauthUri)setSetupUri(r.otpauthUri)}}>Enable MFA</button>{p.mfaEnabled&&<button className="danger" onClick={async()=>{const r=await action(()=>api.disableMfa(mfaPass));if(r){setTimeout(()=>n('/login'),700)}}}>Disable MFA</button>}</div>{setupUri&&<div className="qr-panel"><QRCodeSVG value={setupUri} size={180} includeMargin/><div><p>Scan this QR code, then verify your authenticator code.</p><label>Six-digit code<input inputMode="numeric" maxLength={6} value={enableCode} onChange={e=>setEnableCode(e.target.value.replace(/\D/g,''))}/></label><button disabled={enableCode.length!==6} onClick={async()=>{const r=await action(()=>api.verifyEnableMfa(enableCode));if(r){setP({...p,mfaEnabled:true});setSetupUri('');setEnableCode('')}}}>Verify and enable MFA</button></div></div>}</div>
<div className="card security-card"><h2>MFA email management</h2><p>Change the account email used for sign-in and security communication. Verify your current password before changing it.</p><label>New email<input type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/></label><label>Current password<input type="password" value={emailPass} onChange={e=>setEmailPass(e.target.value)}/></label><button onClick={async()=>{const r=await action(()=>api.changeEmail(emailPass,newEmail));if(r)setP(r)}}>Update email</button></div>
<div className="card security-card"><h2>Change password</h2><p>Your new password must satisfy all required character rules.</p><label>Current password<input type="password" value={oldPass} onChange={e=>setOld(e.target.value)}/></label><label>New password<input type="password" value={newPass} onChange={e=>setNew(e.target.value)}/><PasswordRequirements password={newPass} show={newPass.length>0}/></label><button disabled={!passwordStrong(newPass)} onClick={async()=>{const r=await action(()=>api.changePassword(oldPass,newPass));if(r)setTimeout(()=>n('/login'),900)}}>Change password</button></div>
<div className="card security-card"><h2>Passkey / WebAuthn</h2><p>{passkey===true?'This browser exposes WebAuthn support. Full credential registration requires a production WebAuthn server and credential store.':'This browser does not expose WebAuthn.'}</p><button className="secondary" onClick={()=>{if(passkey)alert('WebAuthn is available in this browser. Server-side credential registration is not enabled in this prototype.')}}>{passkey?'Check passkey capability':'Unavailable'}</button></div>
<div className="card security-card"><h2>Session & security controls</h2><p>Access and refresh tokens are HttpOnly cookies. Tokens are stored server-side only as SHA-256 hashes and can be revoked.</p><div className="mini-actions"><button onClick={async()=>{const r=await action(()=>api.revokeAll());if(r)setTimeout(()=>n('/login'),700)}}>Revoke all sessions</button><button onClick={async()=>{await api.logout().catch(()=>{});n('/login')}}>Sign out this session</button></div></div>
<div className="card security-card"><h2>Account removal</h2><p>Permanently delete this student account and learning progress.</p><label>Current password<input type="password" value={mfaPass} onChange={e=>setMfaPass(e.target.value)}/></label><button className="danger" onClick={async()=>{if(!confirm('Delete your account permanently?'))return;const r=await action(()=>api.deleteAccount(mfaPass));if(r)setTimeout(()=>n('/login'),700)}}>Remove / Delete account</button></div>
<div className="card security-card"><h2>Security architecture</h2><div className="security-list"><div><b>Zero Trust</b><span>Protected API requests require verified authentication.</span></div><div><b>Tokenisation</b><span>Password is never stored; BCrypt stores only a password hash. Access/refresh tokens are opaque random values.</span></div><div><b>RBAC</b><span>Role is attached server-side and exposed as STUDENT for this prototype.</span></div><div><b>RLS direction</b><span>Production PostgreSQL should enforce row-level ownership policies in addition to API authorization.</span></div></div></div></section>{message&&<div className="toast success">{message}</div>}{error&&<div className="toast error">{error}</div>}</>}

function Payment(){const providers=[['PayPal','https://www.paypal.com/au/home'],['Afterpay','https://www.afterpay.com/en-AU'],['Mastercard','https://www.mastercard.com/au/en.html'],['Visa','https://www.visa.com.au/']];return <><div className="page-title"><div><div className="eyebrow">PAYMENT METHOD</div><h1>External payment options</h1><p>No card numbers, CVV, banking credentials or payment tokens are stored by this prototype.</p></div></div><div className="notice"><b>Payment disclaimer:</b> SmartGuide is a learning/decision-support prototype. Use only official provider or insurer payment pages. Do not enter payment-card details into this application.</div><section className="provider-grid">{providers.map(([name,url])=><article className="card provider" key={name}><div className="provider-logo">{name[0]}</div><h2>{name}</h2><p>Open the official {name} website in a new browser tab.</p><a className="cta" href={url} target="_blank" rel="noreferrer">Continue to {name} ↗</a></article>)}</section></>}

function Scenarios(){const[s,setS]=React.useState<Scenario[]>([]);const[x,setX]=React.useState<Scenario|null>(null);const[a,setA]=React.useState<number|null>(null);const[c,setC]=React.useState(3);const[feedback,setFeedback]=React.useState('');const[e,setE]=React.useState('');React.useEffect(()=>{api.scenarios().then(setS).catch(x=>setE(x instanceof Error?x.message:'Could not load scenarios'))},[]);async function done(){if(!x)return;const old=await api.progress().catch(()=>emptyProgress());const q={...old,completedScenarioIds:[...new Set([...old.completedScenarioIds,x.id])],confidenceAfter:c};await api.saveProgress(q).catch(()=>{});setX(null);setA(null);setFeedback('');}return <><div className="page-title"><div><div className="eyebrow">HEALTHCARE MOMENTS</div><h1>Scenarios</h1><p>Practise practical decision-making without using this prototype as medical diagnosis or emergency advice.</p></div></div>{e&&<div className="error">{e}</div>}<div className="scenario-grid">{s.map(v=><button className="scenario-card" key={v.id} onClick={()=>{setX(v);setA(null);setFeedback('')}}><small>{v.moment}</small><h2>{v.title}</h2><p>{v.situation}</p><span>Practise →</span></button>)}</div>{x&&<div className="modal-backdrop"><section className="card modal"><button className="close" onClick={()=>setX(null)}>×</button><small>{x.moment}</small><h2>{x.title}</h2><p>{x.situation}</p><h3>{x.question}</h3>{x.options.map((o,i)=><button className="option" key={o} onClick={()=>setA(i)}>{o}{a===i?' ✓':''}</button>)}{a!==null&&<div className={a===x.correctIndex?'feedback good':'feedback'}><b>{a===x.correctIndex?'Correct direction':'Review this choice'}</b><p>{x.explanation}</p><p><b>Remember:</b> {x.reminder}</p><label>Confidence now: {c}/5<input type="range" min="1" max="5" value={c} onChange={e=>setC(+e.target.value)}/></label><label>Scenario feedback (optional)<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="What was clear or unclear?"/></label><button onClick={done}>Mark scenario complete</button></div>}</section></div>}</>}

function Quiz(){const[s,setS]=React.useState<Scenario[]>([]);const[a,setA]=React.useState<Record<string,number>>({});const[checked,setChecked]=React.useState<Record<string,boolean>>({});const[result,setR]=React.useState<number|null>(null);React.useEffect(()=>{api.scenarios().then(setS)},[]);async function submit(){if(!s.length||s.some(v=>a[v.id]===undefined))return;let ok=0;const wrong:string[]=[];s.forEach(v=>{if(a[v.id]===v.correctIndex)ok++;else wrong.push(v.id)});const score=Math.round(ok/s.length*100);setR(score);const p=await api.progress().catch(()=>emptyProgress());await api.saveProgress({...p,quizBestScore:Math.max(p.quizBestScore,score),quizAttempts:p.quizAttempts+1,lastQuizWrongIds:wrong}).catch(()=>{});}return <><div className="page-title"><div><div className="eyebrow">LEARNING ASSESSMENT</div><h1>OSHC Knowledge Quiz</h1><p>Select an answer to receive immediate feedback, then submit for your score.</p></div></div>{s.map((v,n)=><section className="card quiz-question" key={v.id}><h2>{n+1}. {v.question}</h2>{v.options.map((o,i)=><label className="radio-option" key={o}><input type="radio" name={v.id} checked={a[v.id]===i} onChange={()=>{setA({...a,[v.id]:i});setChecked({...checked,[v.id]:true})}}/><span>{o}</span></label>)}{checked[v.id]&&a[v.id]!==undefined&&<div className={a[v.id]===v.correctIndex?'feedback good':'feedback'}><b>{a[v.id]===v.correctIndex?'Correct':'Not quite'}</b><p>{v.explanation}</p></div>}</section>)}<button disabled={!s.length||s.some(v=>a[v.id]===undefined)} onClick={submit}>Submit quiz</button>{result!==null&&<div className="result card"><b>{result}%</b><span>Your quiz score. Best score and attempts are saved to your account.</span></div>}</>}

function Progress(){const[p,setP]=React.useState<Progress|null>(null);const[s,setS]=React.useState<Scenario[]>([]);React.useEffect(()=>{api.progress().then(setP);api.scenarios().then(setS)},[]);if(!p)return <div className="loading">Loading progress...</div>;const total=s.length||8;const done=p.completedScenarioIds.length;const percent=Math.round(done/total*100);const improving=(p.lastQuizWrongIds||[]).map(id=>s.find(x=>x.id===id)?.title).filter(Boolean) as string[];return <><div className="page-title"><div><div className="eyebrow">LEARNING PROGRESS</div><h1>My Progress</h1><p>Track modules, Healthcare Moments, quiz performance and improvement areas.</p></div></div><div className="metrics"><div className="metric card"><b>{done}/{total}</b><span>Modules completed</span></div><div className="metric card"><b>{percent}%</b><span>Healthcare Moments completed</span></div><div className="metric card"><b>{p.quizBestScore}%</b><span>Best quiz score</span></div></div><section className="card"><h2>Learning progress</h2><div className="progress-bar"><div style={{width:`${percent}%`}}/></div><p>{done} of {total} Healthcare Moments completed.</p></section><section className="card"><h2>Quiz performance</h2><p><b>Attempts:</b> {p.quizAttempts} &nbsp; <b>Best score:</b> {p.quizBestScore}%</p></section><section className="card"><h2>Areas requiring improvement</h2>{improving.length?<ul>{improving.map(x=><li key={x}>{x}</li>)}</ul>:<p>No incorrect topics recorded from the latest submitted quiz.</p>}</section><section className="card"><h2>Confidence</h2><div className="confidence"><div><span>Before</span><strong>{p.confidenceBefore??'—'} / 5</strong></div><div><span>After</span><strong>{p.confidenceAfter??'—'} / 5</strong></div></div></section></>}

class AppErrorBoundary extends React.Component<{children:React.ReactNode},{hasError:boolean;message:string}>{
 state={hasError:false,message:''};
 static getDerivedStateFromError(error:unknown){return {hasError:true,message:error instanceof Error?error.message:'The application could not be loaded.'};}
 render(){if(this.state.hasError)return <div className="auth-page"><div className="auth card"><div className="brand-large"><span className="brand-mark">S</span><b>SECURE OSHC LEARNING</b></div><h1>Application error</h1><p>The page could not be loaded.</p><div className="error">{this.state.message}</div><button onClick={()=>window.location.reload()}>Reload application</button></div></div>;return this.props.children;}
}

function App(){return <BrowserRouter><Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/" element={<Private><Home/></Private>}/><Route path="/profile" element={<Private><Profile/></Private>}/><Route path="/settings" element={<Private><Settings/></Private>}/><Route path="/payment" element={<Private><Payment/></Private>}/><Route path="/scenarios" element={<Private><Scenarios/></Private>}/><Route path="/quiz" element={<Private><Quiz/></Private>}/><Route path="/progress" element={<Private><Progress/></Private>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter>}
const root=document.getElementById('root');
if(root){createRoot(root).render(<React.StrictMode><AppErrorBoundary><App/></AppErrorBoundary></React.StrictMode>);}
